language: ruby

addons:
  code_climate:
    repo_token: 98123461fbec752591c40e3e7af46bcdc6576723bfac2d89c084bfae989e4db3

rvm:
  - 2.5
  - 2.6
  - 2.7

before_install:
  - gem install i18n --no-document

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: bundle exec rspec spec/

after_success:
  after_script:
  - ./cc-test-reporter format-coverage -t simplecov
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
